export const ADD_MESSAGE = 'ADD_MESSAGE';
export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE';

export const LOAD_MESSAGES = 'LOAD_MESSAGES';
export const LOAD_MESSAGES_SUCCESS = 'LOAD_MESSAGES_SUCCESS';
export const LOAD_MESSAGES_FAIL = 'LOAD_MESSAGES_FAIL';

export const LOAD_USERVALIDATION = 'LOAD_USERVALIDATION';
export const LOAD_USERVALIDATION_SUCCESS = 'LOAD_USERVALIDATION_SUCCESS';
export const LOAD_USERVALIDATION_FAIL = 'LOAD_USERVALIDATION_FAIL';

export const CHANGE_IS_MOBILE = 'CHANGE_IS_MOBILE';
export const CHANGE_WIDTH_AND_HEIGHT = 'CHANGE_WIDTH_AND_HEIGHT';

export const USER_SIGNUP = 'USER_SIGNUP';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_DELETE = 'USER_DELETE';

